import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderSection } from "@/components/custom/HeaderSection";
import { getMainRootData } from "@/data/loaders";
import { FooterSection } from "@/components/custom/FooterSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const data = await getMainRootData();
  console.log(data);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderSection data={data.Header} />
        <div>
          {children}
        </div>
        <FooterSection data={data.Footer} />
      </body>
    </html>
  );
}
